### PR TITLE
fix for go1.6 (?) + errors using tardisgo

### PR DESCRIPTION
**Pull request by clemos**
I wanted to test TardisGO, with a fresh install of go 1.6 (from the official Ubuntu 64 PPA) and stumbled upon an issue at compilation with this line, which I somehow fixed.
I'm really no expert in Go, so maybe there's a better way.

This is probably not the right place to ask an unrelated question, but still...
I've been trying to transpile [google safebrowsing](https://github.com/google/safebrowsing) using Tardis Go:
```
tardisgo -trace cmd/sblookup/main.go
```
(I'm aware it's probably a pretty big project to start with, but ...)
I get a bunch of errors such as : 
```
Error : *ssa.Call @ /home/clemos/go/src/github.com/tardisgo/tardisgo/goroot/haxe/go1.4/src/crypto/tls/handshake_client.go:37:20 (Haxe) invalid syntax : "tls: either ServerName or InsecureSkipVerify must be specified in th... 
Error : *ssa.Call @ /home/clemos/go/src/github.com/tardisgo/tardisgo/goroot/haxe/go1.4/src/crypto/tls/handshake_client.go:434:21 (Haxe) invalid syntax : "tls: client certificate private key of type %T does not implement cr... 
Error : *ssa.Call @ /home/clemos/go/src/github.com/tardisgo/tardisgo/goroot/haxe/go1.4/src/crypto/tls/handshake_client.go:274:20 (Haxe) invalid syntax : "tls: server's certificate contains an unsupported type of public key... 
Error : *ssa.Call @ /home/clemos/go/src/github.com/tardisgo/tardisgo/goroot/haxe/go1.4/src/crypto/tls/handshake_server.go:631:26 (Haxe) invalid syntax : "tls: client's certificate's extended key usage doesn't permit it to ... 
Error : *ssa.Call @ /home/clemos/go/src/github.com/tardisgo/tardisgo/goroot/haxe/go1.4/src/crypto/tls/handshake_server.go:644:26 (Haxe) invalid syntax : "tls: client's certificate contains an unsupported public key of type... 
Error : *ssa.BinOp @ /home/clemos/go/src/github.com/tardisgo/tardisgo/goroot/haxe/go1.4/src/encoding/gob/decode.go:1021:63 (Haxe) invalid syntax : " can only be decoded from remote interface type; received concrete t... 
```
I really don't know where to start debugging these errors.
Can you give me a hint ?

### CODE REVIEW

**Comment by elliott5** [comment]
Many thanks Clément, I'll take a look tomorrow.

**Comment by elliott5** [comment]
The good news Clément, is that both the issue you found and the issue with quoted strings (generating all the errors) is now fixed.

The bad news is that I do not think that the generated haxe code will work, this is because the http(s) standard libraries do not work yet.

**Comment by clemos** [comment]
Thanks !
I indeed managed to make it work on another machine (go 1.5), though I stumbled upon another issue (too long filenames or something, I'll make a proper issue later).
